pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test .NET
            image: mcr.microsoft.com/dotnet/sdk:5.0
            caches:
              - dotnetcore
            script:
              - export PROJECT_MD=dddnetcore
              - dotnet restore ./dddnetcore
              - dotnet build $PROJECT_MD
        - step:
            name: Build and Test SPA
            image: node:18.0.0
            caches:
              - node
            script:
              - npm --prefix ./spa install
              - npm --prefix ./spa install @angular/cli -g
              - npm --prefix ./spa run build
            artifacts:
              - node_modules/ # Save modules for next steps
#        - step:
#            name: Build and Test NodeJS
#            image: node:18.0.0
#            caches:
#              - node
#            script:
#              - npm --prefix ./bulletproof-nodejs install
#              - npm --prefix ./bulletproof-nodejs run test
#            artifacts:
#              - node_modules/ # Save modules for next steps
#    - step:
#        name: Deploy to production
#        deployment: production
#        script:
#          - echo "Deploying to production environment"
#          - pipe: atlassian/ssh-run:0.2.2
#            variables:
#              SSH_USER: 'root'
#              SERVER: 'vsgate-ssh.dei.isep.ipp.pt:10616'
#              COMMAND: '~/lei_isep_2022_23_lapr5_22s5_3de_33/deploy.sh'